M48
; #@! TF.GenerationSoftware,LibrePCB,LibrePCB,1.1.0
; #@! TF.CreationDate,2024-04-23T21:01:02
; #@! TF.ProjectId,motherboard (Version 1),d5d7f40e-06e5-483f-b774-8957b2c1e08f,version_2
; #@! TF.Part,Single
; #@! TF.SameCoordinates
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC,TZ
; #@! TA.AperFunction,MechanicalDrill
T1C1.0
%
G90
G05
M71
T1
X11.7Y73.8
X35.8Y22.8
X9.2Y22.8
X33.7Y73.8
T0
M30
